@startuml
class Cart {
  -id : CustomerId
  +addProduct(product : Product, quantity : int)
  +numberOfItems() : int
  +subTotal() : Money
}

Cart *-  CartItem

class CartItem {
  -quantity : int
  +increaseQuantityBy(value : int)
  +subTotal() : Money
}

CartItem -> Product

class Product {
  -id : ProductId
  -name : String
  -description : String
  -itemsInStock : int
}

Product --> Money : price

class Money {
  -currency : Currency
  -amount : BigDecimal
}
@enduml